---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  database:  {{ "postgres" | b64enc }}
  host: {{ include "postgres.fullname" . | b64enc }}
  username: {{ .Values.pg.db_user | b64enc }}
  password: {{ .Values.pg.db_password | b64enc }}
  port: {{ print .Values.service.port | b64enc }}