apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-mg
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.managementService.type }}
  ports:
    - port: {{ .Values.managementService.port }}
      targetPort: tcp-manag-port
      protocol: TCP
      name: tcp-manag-port
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
