---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  host: {{ include "rabbitmq.fullname" . | b64enc }}
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}
  port: {{ print .Values.service.port | b64enc }}